import { mkdirSync, writeFileSync, readdirSync, watch } from "fs";
import path from "path";
import type { Plugin } from "vite";

const MOCKUPS_DIR = "src/components/mockups";
const GENERATED_MODULE = "src/.generated/mockup-components.ts";

interface DiscoveredComponent {
  globKey: string;
  importPath: string;
}

function walkMockups(dir: string, base: string): string[] {
  let results: string[] = [];
  let entries: ReturnType<typeof readdirSync>;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return results;
  }
  for (const entry of entries) {
    if (entry.name.startsWith("_")) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results = results.concat(walkMockups(full, base));
    } else if (entry.isFile() && entry.name.endsWith(".tsx")) {
      results.push(path.relative(base, full));
    }
  }
  return results;
}

export function mockupPreviewPlugin(): Plugin {
  let root = "";
  let currentSource = "";
  let watcher: ReturnType<typeof watch> | null = null;

  function getMockupsAbsDir(): string {
    return path.join(root, MOCKUPS_DIR);
  }

  function getGeneratedModuleAbsPath(): string {
    return path.join(root, GENERATED_MODULE);
  }

  function discoverComponents(): Array<DiscoveredComponent> {
    const mockupsAbs = getMockupsAbsDir();
    const files = walkMockups(mockupsAbs, path.join(root, "src"));
    return files.map((f) => {
      const posix = f.split(path.sep).join("/");
      return {
        globKey: "./" + posix,
        importPath: path.posix.relative(".generated", posix),
      };
    });
  }

  function generateSource(components: Array<DiscoveredComponent>): string {
    const entries = components
      .map(
        (c) =>
          `  ${JSON.stringify(c.globKey)}: () => import(${JSON.stringify(c.importPath)})`
      )
      .join(",\n");

    return [
      "// This file is auto-generated by mockupPreviewPlugin.ts.",
      "type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;",
      "export const modules: ModuleMap = {",
      entries,
      "};",
      "",
    ].join("\n");
  }

  function shouldAutoRescan(pathname: string): boolean {
    return (
      pathname.includes("/components/mockups/") ||
      pathname.includes("/.generated/mockup-components")
    );
  }

  let refreshInFlight = false;
  let refreshQueued = false;

  function refresh(): boolean {
    if (refreshInFlight) {
      refreshQueued = true;
      return false;
    }

    refreshInFlight = true;
    let changed = false;
    try {
      const components = discoverComponents();
      const newSource = generateSource(components);
      if (newSource !== currentSource) {
        currentSource = newSource;
        const generatedModuleAbsPath = getGeneratedModuleAbsPath();
        mkdirSync(path.dirname(generatedModuleAbsPath), { recursive: true });
        writeFileSync(generatedModuleAbsPath, currentSource);
        changed = true;
      }
    } finally {
      refreshInFlight = false;
    }

    if (refreshQueued) {
      refreshQueued = false;
      const followUp = refresh();
      return changed || followUp;
    }

    return changed;
  }

  return {
    name: "mockup-preview",
    enforce: "pre",

    configResolved(config) {
      root = config.root;
    },

    buildStart() {
      refresh();
    },

    configureServer(viteServer) {
      refresh();

      const mockupsAbsDir = getMockupsAbsDir();
      mkdirSync(mockupsAbsDir, { recursive: true });

      try {
        watcher = watch(mockupsAbsDir, { recursive: true }, (_evt, filename) => {
          if (filename && filename.endsWith(".tsx")) {
            refresh();
          }
        });
      } catch {
        // fs.watch with recursive may not be available on all platforms — safe to skip
      }

      viteServer.middlewares.use((req, res, next) => {
        const requestUrl = new URL(req.url ?? "/", "http://127.0.0.1");
        const pathname = requestUrl.pathname;
        const originalEnd = res.end.bind(res);

        res.end = ((...args: Parameters<typeof originalEnd>) => {
          if (res.statusCode === 404 && shouldAutoRescan(pathname)) {
            refresh();
          }
          return originalEnd(...args);
        }) as typeof res.end;

        next();
      });
    },

    closeWatcher() {
      if (watcher) {
        watcher.close();
      }
    },
  };
}
