// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/architecture/Diagram.tsx": () => import("../components/mockups/architecture/Diagram.tsx"),
  "./components/mockups/vault-ui/DarkPremium.tsx": () => import("../components/mockups/vault-ui/DarkPremium.tsx"),
  "./components/mockups/vault-ui/RefinedLight.tsx": () => import("../components/mockups/vault-ui/RefinedLight.tsx"),
  "./components/mockups/vault-ui/VibrantGradient.tsx": () => import("../components/mockups/vault-ui/VibrantGradient.tsx")
};
